IDIR =../include
CC =gcc
CFLAGS =-I$(IDIR)

ODIR =obj
LDIR =../lib

LIBS =

_DEPS = alu.h
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))

_OBJ = alu.o main.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))

$(ODIR)/%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

alumake: $(OBJ)
	gcc -o $@ $^ $(CFLAGS) $(LIBS)

.PHONY: clean

clean:
	rm -f $(ODIR)/*.o *~ core $(INCDIR)/*~
